image: registry.gitlab.com/kitsune_other/kitsune_docker_unittest:0.1.0

build:
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME

    - cd /builds/tobiasanker/libKitsunemimiCommon
    - ./build.sh test

    - /builds/tobiasanker/build/libKitsunemimiCommon/tests/unit_tests/unit_tests
    - /builds/tobiasanker/build/libKitsunemimiCommon/tests/memory_leak_tests/memory_leak_tests

  tags:
    - docker
