image: registry.gitlab.com/kitsune_other/kitsune_docker_unittest:0.1.0

build:
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME

    - cd /builds/tobiasanker/libKitsuneCommon
    - ./build.sh

    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'/builds/result'
    - /builds/tobiasanker/build/libKitsuneCommon/tests/tests

  tags:
    - docker
